### ISSUE TITLE
HTML errors

### ISSUE THREAD

**Issue by aiddun** [jvde-github/AIS-catcher#317]
Just updated to master, and now I'm getting these errors which is turning the map black and UI responsive, I assume it's because of loadPlugins

```
Starting plugin code
script_v0_60_159_gb2f03e82.js:38 Uncaught ReferenceError: loadPlugins is not defined
    at script_v0_60_159_gb2f03e82.js:38:4382Understand this error
ships.dunlap.ai/:1 <meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes">Understand this warning
script_v0_60_159_gb2f03e82.js:14 Uncaught TypeError: Cannot read properties of undefined (reading 'getView')
    at updateMapURL (script_v0_60_159_gb2f03e82.js:14:50410)
    at saveSettings (script_v0_60_159_gb2f03e82.js:14:51052)
    at activateTab (script_v0_60_159_gb2f03e82.js:14:82530)
    at HTMLElement.onclick ((index):8:86)Understand this error
2script_v0_60_159_gb2f03e82.js:14 Uncaught TypeError: Cannot read properties of undefined (reading 'getView')
    at HTMLButtonElement.<anonymous> (script_v0_60_159_gb2f03e82.js:14:78224)Understand this error```

**Comment by aiddun** [comment]
Fixed, thanks!
